apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/secret.yaml
- manifests/postgres-statefulset.yaml
- manifests/postgres-service.yaml
- manifests/todo-backend-configmap.yaml
- manifests/kustom-deployment.yaml
- manifests/todo-backend-ingress.yaml
- manifests/todo-backend-service.yaml
#images:
#- name: gcr.io/PROJECT_ID/IMAGE
#  newName: cdaniel999/todo-backend:latest