apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-application
  template:
    metadata:
      labels:
        app: todo-application
    spec:
      volumes:
        - name: todo-app-image
          persistentVolumeClaim:
            claimName: todo-image-claim
      #initContainers:
      #  - name: wait-for-services
      #    image: busybox
      #    command: ["/bin/sh","-c"]
      #    args: ["until echo 'Waiting for postgres...' && nc -vz -w 2 postgres 5432 do echo 'Looping forever...'; sleep 2; done;"]
      containers:
        - name: todo-application
          image: cdaniel999/todo-app:latest
          imagePullPolicy: "Always"
          volumeMounts:
          - name: todo-app-image
            mountPath: /app/files
          env:
           - name: FLASK_ENV
             valueFrom:
              configMapKeyRef:
               name: todo-app-configmap
               key: flask-env
           - name: FLASK_RUN_HOST
             valueFrom:
              configMapKeyRef:
               name: todo-app-configmap
               key: flask-run-host
           - name: FLASK_RUN_PORT
             valueFrom:
              configMapKeyRef:
               name: todo-app-configmap
               key: flask-run-port
           - name: APP_SETTINGS
             valueFrom:
              configMapKeyRef:
               name: todo-app-configmap
               key: app-settings
           - name: POSTGRES_HOST
             value: postgres-svc
           - name: POSTGRES_USER
             valueFrom:
              secretKeyRef:
                key: user
                name: postgres-credentials
           - name: POSTGRES_PASSWORD
             valueFrom:
              secretKeyRef:
                key: password
                name: postgres-credentials