apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-app-dep
  namespace: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-app
  template:
    metadata:
      labels:
        app: log-output-app
    spec:
      volumes:
        - name: log-shared-data
          persistentVolumeClaim:
            claimName: log-shared-volume-claim
        - name: config
          configMap:
            name: log-output-app-configmap
            # An array of keys from the ConfigMap to create as files
            items:
            - key: "information.txt"
              path: "information.txt"
      containers:
        - name: log-generator
          image: cdaniel999/log-generator:latest
          volumeMounts:
          - name: log-shared-data
            mountPath: /app/files
          imagePullPolicy: "Always"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
        - name: log-reader
          image: cdaniel999/log-reader:latest
          volumeMounts:
          - name: config
            mountPath: "/app/config"
            readOnly: true
          - name: log-shared-data
            mountPath: /app/files
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-app-configmap
                  key: message
            - name: PINGPONG_APP_URL
              valueFrom:
                configMapKeyRef:
                  name: log-output-app-configmap
                  key: pingpong_app_url
            - name: PINGPONG_APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: log-output-app-configmap
                  key: pingpong_app_port
            - name: CONFIG_PATH
              valueFrom:
                configMapKeyRef:
                  name: log-output-app-configmap
                  key: config-path
          imagePullPolicy: "Always"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
