apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-image-claim # name of the volume claim, this will be used in the deployment
  namespace: todo-app
spec:
  storageClassName: standard-rwo # this is the name of the persistent volume we are claiming
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Mi