apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pingpong-volume-claim # name of the volume claim, this will be used in the deployment
spec:
  storageClassName: my-k3d-pv3 # this is the name of the persistent volume we are claiming
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi