apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pingpong-app-dep
  namespace: log-output
spec:
  template:
    metadata:
      labels:
        app: pingpong-app
    spec:
      containers:
        - name: pingpong-app
          image: cdaniel999/pinpong-app-svrless:latest
          imagePullPolicy: "Always"
          # readinessProbe:
          #   initialDelaySeconds: 10 # Initial delay until the readiness is tested
          #   periodSeconds: 5 # How often to test
          #   httpGet:
          #      path: /health
          #      port: 8080
          # livenessProbe:
          #   initialDelaySeconds: 20 # Initial delay until the liveness is tested
          #   periodSeconds: 5 # How often to test
          #   httpGet:
          #      path: /health
          #      port: 5000
          env:
           - name: FLASK_ENV
             valueFrom:
              configMapKeyRef:
               name: pingpong-app-configmap
               key: flask-env
           - name: FLASK_RUN_HOST
             valueFrom:
              configMapKeyRef:
               name: pingpong-app-configmap
               key: flask-run-host
           - name: FLASK_RUN_PORT
             valueFrom:
              configMapKeyRef:
               name: pingpong-app-configmap
               key: flask-run-port
           - name: APP_SETTINGS
             valueFrom:
              configMapKeyRef:
               name: pingpong-app-configmap
               key: app-settings
           - name: POSTGRES_HOST
             valueFrom:
              configMapKeyRef:
               name: pingpong-app-configmap
               key: postgres-host
           - name: POSTGRES_USER
             valueFrom:
              secretKeyRef:
                key: user
                name: postgres-credentials
           - name: POSTGRES_PASSWORD
             valueFrom:
              secretKeyRef:
                key: password
                name: postgres-credentials
          # resources:
          #   limits:
          #     memory: "256Mi"
          #     cpu: "250m"
          #   requests:
          #     memory: "128Mi"
          #     cpu: "250m"