apiVersion: v1
kind: Pod
metadata:
  name: my-busybox
  namespace: todo-app
  labels:
    app: my-busybox
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    #restartPolicy: Always
    resources:
      limits:
        memory: "100Mi"
        cpu: "100m"
      requests:
        memory: "50Mi"
        cpu: "50m"