apiVersion: v1
kind: Service
metadata:
  name: todo-backend-svc
  namespace: todo-app
spec:
  type: NodePort
  selector:
    app: todo-backend-dep
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP