apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-shared-volume-claim
  namespace: log-output
spec:
  #storageClassName: my-k3d-pv2 # this is the name of the persistent volume we are claiming
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi