apiVersion: v1
kind: Service
metadata:
  name: log-output-app-svc
  namespace: log-output
spec:
  type: NodePort
  selector:
    app: log-output-app
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP