apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage-analysis
  namespace: todo-app
spec:
  metrics:
  - name: cpu-usage-analysis
    initialDelay: 10m
    successCondition: "len(result) > 0 ? result[0] < 1.2 : true"
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1736-prometheus.prometheus.svc.cluster.local:9090 # DNS name for my Prometheus, find yours with kubectl describe svc ...
        query: |
            sum(rate(container_cpu_usage_seconds_total{container!="", namespace="todo-app"}[10m]))*100