services:
  todo-application:
    build: .
    ports:
     - 5000:5000
    environment:
      POSTGRES_HOST: "todo-postgres"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-example}"
      APP_SETTINGS: "${POSTGRES_PASSWORD:-config.DevelopmentConfig}"
    depends_on:
      todo-postgres:
        condition: service_started
  todo-postgres:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-example}"
    container_name: todo-postgres 