# Execute 'docker exec k3d-k3s-default-agent-0 mkdir -p /tmp/kube' to create the directory on the node
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k3d-pv
spec:
  storageClassName: my-k3d-pv # this is the name you are using later to claim this volume
  capacity:
    storage: 300Mi # Could be e.q. 500Gi. Small amount is to preserve space when testing locally
  volumeMode: Filesystem # This declares that it will be mounted into pods as a directory
  accessModes:
  - ReadWriteOnce
  local:
    path: /tmp/kube
  nodeAffinity: ## This is only required for local, it defines which nodes can access it
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-k3s-default-agent-0