
name: Delete namespace contents for deleted branch in GKE

on:
  delete:
    branches:
      - develop
      - staging

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  IMAGE: todo-backend
  APP_PATH: ./part_3/todo-backend

jobs:
  setup-delete-branch:
    name: Delete branch namespace
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # Note: the delete trigger does not transmit the branch name on which the delete was triggered but assumes default branch.
    # This is why the branch name has to be extracted from context
    - name: Github context
      run: echo "${{ toJson(github) }}"
    
    - name: Set Branch name
      run: |
          BRANCH=$(cat ${{ github.event_path }} | jq --raw-output '.ref')
          echo "${{ github.repository }} has ${BRANCH} branch"
          echo "STAGE=$(echo ${BRANCH})" >> $GITHUB_ENV

    - name: Echo Branch name
      run: echo Deleting from Kubernetes $STAGE


    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    # Install gke-gcloud-auth-plugin
    - name: Install gke-gcloud-auth-plugin
      run: |-
        gcloud components install gke-gcloud-auth-plugin

    # Delete branch resources from cluster
    - name: Delete
      run: |-
       gcloud container clusters get-credentials $GKE_CLUSTER --zone=$GKE_ZONE
       kubectl config set-context --namespace $STAGE --current 
       kubectl delete all --all -n --namespace=$STAGE